version: "3.8"

services:
  camera-manager:
    container_name: camera-manager
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "python", "src/main.py" ]
    volumes:
      - .:/app