version: "3.8"

services:
  camera-manager:
    container_name: camera-manager
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    command: [ "npm", "run", "dev" ]
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules